#!/bin/bash
# This file is supposed to be executed in the container
COUNT=`cat /proc/1/cgroup | awk -F':' '{print $3}' | grep '^/docker' | wc -l`
if [ $COUNT -eq 0 ]
then
    echo "Script should be run inside a docker container"
    exit 1
fi
# install heavy packages used by gateway
mkdir -p /root/dummy/gateway && cd /root/dummy/gateway && \
    npm config set python /usr/bin/python2.7 && \
    npm install --unsafe-perm node-gyp@3.8.0 sqlite3@4.1.0 bufferutil@4.0.1
