#!/bin/bash
DOCKERFILE=Dockerfile-rpi-crossbuild
TAG=rpi-ui-latest
TARGET_ARCH=linux/arm/v7
BUILDER=$(docker buildx ls | grep -o "${TARGET_ARCH}")
if [ -z ${BUILDER} ]
then
    echo "No docker builder found for '${TARGET_ARCH}'. Please ensure 'docker buildx' is configured properly"
    exit 1
fi
TIMESTAMP=`date +"%Y%m%d%H%M%S"`
docker build -f $DOCKERFILE --pull --force-rm=true --rm=true --build-arg TIMESTAMP=$TIMESTAMP -t apendergast/ceg-docker-base:$TAG .
