#!/bin/bash
# This file is supposed to be executed in the container
COUNT=`cat /proc/1/cgroup | awk -F':' '{print $3}' | grep '^/docker' | wc -l`
if [ $COUNT -eq 0 ]
then
    echo "Script should be run inside a docker container"
    exit 1
fi
# install heavy packages used by ui
mkdir -p /root/dummy/ui && cd /root/dummy/ui && \
    npm config set python /usr/bin/python2.7 && \
    npm install --unsafe-perm webpack@3.5.3 webpack-dev-server@2.7.1 node-gyp@3.8.0 node-sass@4.14.1 babel-core@6.25.0
